const pages = [
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Importing the Hyv Core Module](#importing-the-hyv-core-module)\n  * [Creating a Hyv Agent](#creating-a-hyv-agent)\n  * [Assigning a Task to the Agent](#assigning-a-task-to-the-agent)\n- [Expected Output](#expected-output)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "01_GETTING_STARTED",
		page: "pages/01_GETTING_STARTED.md",
		title: "01 getting started",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Setting Up a Language Model](#setting-up-a-language-model)\n  * [Creating a System Instruction](#creating-a-system-instruction)\n  * [Guiding the Model's Responses](#guiding-the-models-responses)\n- [Expected Output](#expected-output)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "02_SYSTEM_INSTRUCTIONS",
		page: "pages/02_SYSTEM_INSTRUCTIONS.md",
		title: "02 system instructions",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Import Necessary Modules](#import-necessary-modules)\n  * [Create an Agent](#create-an-agent)\n  * [Run the Sequence](#run-the-sequence)\n  * [Add More Agents](#add-more-agents)\n- [Expected Output](#expected-output)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "03_CREATING_A_SEQUENCE",
		page: "pages/03_CREATING_A_SEQUENCE.md",
		title: "03 creating a sequence",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Connecting to the Vector Database](#connecting-to-the-vector-database)\n  * [Creating Classes to store Messages](#creating-classes-to-store-messages)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "04_a_SETUP_WEAVIATE_VECTOR_DATABASE",
		page: "pages/04_a_SETUP_WEAVIATE_VECTOR_DATABASE.md",
		title: "04 a setup weaviate vector database",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Configuring the Conversational Agent](#configuring-the-conversational-agent)\n  * [Managing User Interactions](#managing-user-interactions)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "04_b_USING_WEAVIATE_VECTOR_DATABASE",
		page: "pages/04_b_USING_WEAVIATE_VECTOR_DATABASE.md",
		title: "04 b using weaviate vector database",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Install Hyv Dependencies](#install-hyv-dependencies)\n  * [Import Modules](#import-modules)\n  * [Create DallEModelAdapter](#create-dall-e-model-adapter)\n  * [Set up an Agent](#set-up-an-agent)\n  * [Assign Task to Agent](#assign-task-to-agent)\n- [Expected Output](#expected-output)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "05_GENERATE_IMAGES_WITH_DALL-E",
		page: "pages/05_GENERATE_IMAGES_WITH_DALL-E.md",
		title: "05 generate images with dall e",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Import Required Modules](#import-required-modules)\n  * [Establish an Image Writer](#establish-an-image-writer)\n  * [Create an Agent](#create-an-agent)\n  * [Generate Images](#generate-images)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "06_GENERATING_IMAGES_WITH_STABLE-DIFFUSION",
		page: "pages/06_GENERATING_IMAGES_WITH_STABLE-DIFFUSION.md",
		title: "06 generating images with stable diffusion",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Setting Competition Instructions](#setting-competition-instructions)\n  * [Creating a Helper Function](#creating-a-helper-function)\n  * [Generating Competition Entries](#generating-competition-entries)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "07_a_LET_AI_AGENTS_COMPETE_GENERATED_CONTENT",
		page: "pages/07_a_LET_AI_AGENTS_COMPETE_GENERATED_CONTENT.md",
		title: "07 a let ai agents compete generated content",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Creating Instructions for Jurors](#creating-instructions-for-jurors)\n  * [Judging the Entries](#judging-the-entries)\n  * [Determining the Winner](#determining-the-winner)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "07_b_LET_AI_AGENTS_RATE_GENERATED_CONTENT",
		page: "pages/07_b_LET_AI_AGENTS_RATE_GENERATED_CONTENT.md",
		title: "07 b let ai agents rate generated content",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Import Required Modules](#import-required-modules)\n  * [Set Up a Mathematical Model](#set-up-a-mathematical-model)\n  * [Create an Agent](#create-an-agent)\n  * [Assign a Problem to the Agent](#assign-a-problem-to-the-agent)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "08_MAKING_PRECISE_CALCULATIONS",
		page: "pages/08_MAKING_PRECISE_CALCULATIONS.md",
		title: "08 making precise calculations",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Import Necessary Modules](#import-necessary-modules)\n  * [Design the Persona](#design-the-persona)\n  * [Generate Persona Instructions](#generate-persona-instructions)\n  * [Instantiate a Hyv Agent](#instantiate-a-hyv-agent)\n  * [Assign Tasks to the Agent](#assign-tasks-to-the-agent)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "09_CREATING_PERSONAS",
		page: "pages/09_CREATING_PERSONAS.md",
		title: "09 creating personas",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Importing Necessary Libraries](#importing-necessary-libraries)\n  * [Specifying Agent Instructions](#specifying-agent-instructions)\n  * [Establishing Concurrent Agents](#establishing-concurrent-agents)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "10_a_PARALLEL_AGENTS_WORKING_TOGETHER",
		page: "pages/10_a_PARALLEL_AGENTS_WORKING_TOGETHER.md",
		title: "10 a parallel agents working together",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Formulating a Function to Assign Tasks](#formulating-a-function-to-assign-tasks)\n  * [Delegating Tasks to Agents](#delegating-tasks-to-agents)\n  * [Unifying the Outcomes](#unifying-the-outcomes)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "10_b_PARALLEL_AGENTS_WORK_MERGED_TOGETHER",
		page: "pages/10_b_PARALLEL_AGENTS_WORK_MERGED_TOGETHER.md",
		title: "10 b parallel agents work merged together",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Importing Required Modules](#importing-required-modules)\n  * [Establishing the Developer and Optimizer Agents](#establishing-the-developer-and-optimizer-agents)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "11_a_OPTIMIZE_GENERATED_CODE",
		page: "pages/11_a_OPTIMIZE_GENERATED_CODE.md",
		title: "11 a optimize generated code",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Assigning Tasks to Agents for Code Optimization](#assigning-tasks-to-agents-for-code-optimization)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "11_b_OPTIMIZE_GENERATED_CODE",
		page: "pages/11_b_OPTIMIZE_GENERATED_CODE.md",
		title: "11 b optimize generated code",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Understanding Verbosity Levels](#understanding-verbosity-levels)\n  * [Setting Verbosity Levels](#setting-verbosity-levels)\n  * [Logging Details per Verbosity Level](#logging-details-per-verbosity-level)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "12_UNDERSTANDING_VERBOSITY_OF_HYV_AGENTS",
		page: "pages/12_UNDERSTANDING_VERBOSITY_OF_HYV_AGENTS.md",
		title: "12 understanding verbosity of hyv agents",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Creating an Agent](#creating-an-agent)\n  * [Assigning a Task](#assigning-a-task)\n  * [Retrieving the Answer](#retrieving-the-answer)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "13_a_ASSIGNING_A_TASK_TO_AN_AGENT",
		page: "pages/13_a_ASSIGNING_A_TASK_TO_AN_AGENT.md",
		title: "13 a assigning a task to an agent",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Creating an Agent](#creating-an-agent)\n  * [Assigning a Task](#assigning-a-task)\n  * [Executing the Task](#executing-the-task)\n  * [Retrieving the Answer](#retrieving-the-answer)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "13_b_ASSIGNING_A_TASK_TO_AN_AGENT",
		page: "pages/13_b_ASSIGNING_A_TASK_TO_AN_AGENT.md",
		title: "13 b assigning a task to an agent",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Installing Required Packages](#installing-required-packages)\n  * [Importing Essential Modules](#importing-essential-modules)\n  * [Constructing Helper Functions](#constructing-helper-functions)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "14_a_GENERATE_A_STORY_WITH_INLINE_IMAGES",
		page: "pages/14_a_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		title: "14 a generate a story with inline images",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Developing the Story Creation and Illustration Agents](#developing-the-story-creation-and-illustration-agents)\n  * [Defining the Image Placement Function](#defining-the-image-placement-function)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "14_b_GENERATE_A_STORY_WITH_INLINE_IMAGES",
		page: "pages/14_b_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		title: "14 b generate a story with inline images",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Initiating the Sequence and Story Generation](#initiating-the-sequence-and-story-generation)\n  * [Executing the Script](#executing-the-script)\n  * [Verifying the Output](#verifying-the-output)\n  * [Handling Errors](#handling-errors)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "14_c_GENERATE_A_STORY_WITH_INLINE_IMAGES",
		page: "pages/14_c_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		title: "14 c generate a story with inline images",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Initializing the SongModelAdapter](#initializing-the-song-model-adapter)\n  * [Task Assignment to the SongModelAdapter](#task-assignment-to-the-song-model-adapter)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "15_a_CREATING_CUSTOM_MODEL_ADAPTERS",
		page: "pages/15_a_CREATING_CUSTOM_MODEL_ADAPTERS.md",
		title: "15 a creating custom model adapters",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Incorporating the SongModelAdapter](#incorporating-the-song-model-adapter)\n  * [Creating an Agent and Initiating the Sequence](#creating-an-agent-and-initiating-the-sequence)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "15_b_CREATING_CUSTOM_MODEL_ADAPTERS",
		page: "pages/15_b_CREATING_CUSTOM_MODEL_ADAPTERS.md",
		title: "15 b creating custom model adapters",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Installing Necessary Dependencies](#installing-necessary-dependencies)\n  * [Initiation of the MongoDB Store Adapter](#initiation-of-the-mongo-db-store-adapter)\n  * [Defining the Mongoose Schema and Model](#defining-the-mongoose-schema-and-model)\n  * [Forming the MongoDB Store Adapter Class](#forming-the-mongo-db-store-adapter-class)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "16_a_CREATING_A_MONGODB_STORE_ADAPTER",
		page: "pages/16_a_CREATING_A_MONGODB_STORE_ADAPTER.md",
		title: "16 a creating a mongodb store adapter",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Implementing the Set Method](#implementing-the-set-method)\n  * [Implementing the Get Method](#implementing-the-get-method)\n- [Connecting to MongoDB](#connecting-to-mongo-db)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "16_b_CREATING_A_MONGODB_STORE_ADAPTER",
		page: "pages/16_b_CREATING_A_MONGODB_STORE_ADAPTER.md",
		title: "16 b creating a mongodb store adapter",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Configuring Prisma](#configuring-prisma)\n  * [Defining the Prisma Model](#defining-the-prisma-model)\n  * [Generating the Prisma Client](#generating-the-prisma-client)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "17_a_CREATING_A_PRISMA_STORE_ADAPTER",
		page: "pages/17_a_CREATING_A_PRISMA_STORE_ADAPTER.md",
		title: "17 a creating a prisma store adapter",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Initiating the Prisma Store Adapter](#initiating-the-prisma-store-adapter)\n  * [Implementing the Set Method](#implementing-the-set-method)\n  * [Implementing the Get Method](#implementing-the-get-method)\n- [Using the Prisma Store Adapter](#using-the-prisma-store-adapter)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "17_b_CREATING_A_PRISMA_STORE_ADAPTER",
		page: "pages/17_b_CREATING_A_PRISMA_STORE_ADAPTER.md",
		title: "17 b creating a prisma store adapter",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Setting Up Required Imports](#setting-up-required-imports)\n  * [Constructing an Agent with Persona](#constructing-an-agent-with-persona)\n  * [Initiating Readline Interface](#initiating-readline-interface)\n  * [Implementing the Chat Function](#implementing-the-chat-function)\n  * [Starting the Chat](#starting-the-chat)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "18_CREATING_A_SIMPLE_CHAT_WITH_PERSONA",
		page: "pages/18_CREATING_A_SIMPLE_CHAT_WITH_PERSONA.md",
		title: "18 creating a simple chat with persona",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Recognizing Hyv's Error Pattern](#recognizing-hyvs-error-pattern)\n  * [Catching Errors](#catching-errors)\n  * [Understanding Errors](#understanding-errors)\n  * [Logging Errors](#logging-errors)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "19_HANDLING_ERRORS",
		page: "pages/19_HANDLING_ERRORS.md",
		title: "19 handling errors",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [The Philosophy of Hyv](#the-philosophy-of-hyv)\n  * [The Hyv Ecosystem](#the-hyv-ecosystem)\n  * [Collective Intelligence in Action](#collective-intelligence-in-action)\n  * [Expansive Applications](#expansive-applications)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "20_WHAT_DOES_HYV_MEAN_WHAT_IS_HYV",
		page: "pages/20_WHAT_DOES_HYV_MEAN_WHAT_IS_HYV.md",
		title: "20 what does hyv mean what is hyv",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Implementing the `before` Method](#implementing-the-before-method)\n  * [Using the `after` Method](#using-the-after-method)\n  * [Leveraging the `finally` Method](#leveraging-the-finally-method)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "21_BEFORE_AFTER_FINALLY_METHODS_OF_AGENT",
		page: "pages/21_BEFORE_AFTER_FINALLY_METHODS_OF_AGENT.md",
		title: "21 before after finally methods of agent",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Creating an Agent](#creating-an-agent)\n  * [Setting Up a Serverless Function](#setting-up-a-serverless-function)\n  * [Utilizing the REST API](#utilizing-the-rest-api)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "22_HYV_REST_API_NEXTJS_API_ROUTE_SERVERLESS",
		page: "pages/22_HYV_REST_API_NEXTJS_API_ROUTE_SERVERLESS.md",
		title: "22 hyv rest api nextjs api route serverless",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Creating an Agent](#creating-an-agent)\n  * [Setting Up an Express Server](#setting-up-an-express-server)\n  * [Creating a Route](#creating-a-route)\n  * [Starting the Server](#starting-the-server)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "23_HYV_REST_API_EXPRESSJS_SERVER",
		page: "pages/23_HYV_REST_API_EXPRESSJS_SERVER.md",
		title: "23 hyv rest api expressjs server",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Modifying the GPTModelAdapter](#modifying-the-gpt-model-adapter)\n    + [Adjusting the Temperature](#adjusting-the-temperature)\n  * [Tailoring the Agent](#tailoring-the-agent)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "24_ADJUSTING_MODEL_ADAPTER_OPTIONS",
		page: "pages/24_ADJUSTING_MODEL_ADAPTER_OPTIONS.md",
		title: "24 adjusting model adapter options",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Modifying Side Effects](#modifying-side-effects)\n  * [Customizing `before`, `after` and `finally` Functions](#customizing-before-after-and-finally-functions)\n  * [Switching the Model](#switching-the-model)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "25_ADJUSTING_AGENT_OPTIONS",
		page: "pages/25_ADJUSTING_AGENT_OPTIONS.md",
		title: "25 adjusting agent options",
	},
	{
		toc: "- [Multi-Agent Story Creation and Visualization](#multi-agent-story-creation-and-visualization)\n- [Automated E-Learning Content Creation](#automated-e-learning-content-creation)\n- [Intelligent Social Media Management](#intelligent-social-media-management)\n- [Automated Market Research](#automated-market-research)\n- [Comprehensive Customer Support System](#comprehensive-customer-support-system)",
		name: "26_ADVANCED_USE_CASES_FOR_HYV_AGENTS",
		page: "pages/26_ADVANCED_USE_CASES_FOR_HYV_AGENTS.md",
		title: "26 advanced use cases for hyv agents",
	},
	{
		toc: "- [The Beehive Inspiration](#the-beehive-inspiration)\n- [Harnessing Collective Intelligence](#harnessing-collective-intelligence)\n- [A Central Hub for AI Models](#a-central-hub-for-ai-models)\n- [Streamlined Task Management](#streamlined-task-management)\n- [Flexible, Plug-and-Play Architecture](#flexible-plug-and-play-architecture)\n- [Broad Compatibility](#broad-compatibility)",
		name: "27_SIMPLICITY_POWERFUL_HIGH_POTENTIAL_OF_HYV_AGENTS",
		page: "pages/27_SIMPLICITY_POWERFUL_HIGH_POTENTIAL_OF_HYV_AGENTS.md",
		title: "27 simplicity powerful high potential of hyv agents",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Importing the Necessary Modules](#importing-the-necessary-modules)\n  * [Establishing Agents](#establishing-agents)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "28_a_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER",
		page: "pages/28_a_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER.md",
		title: "28 a ai debate two agents talking to each other",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Initiating the Debate](#initiating-the-debate)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "28_b_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER",
		page: "pages/28_b_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER.md",
		title: "28 b ai debate two agents talking to each other",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Importing the Necessary Modules](#importing-the-necessary-modules)\n  * [Defining the Persona Characteristics](#defining-the-persona-characteristics)\n  * [Creating Persona Instructions](#creating-persona-instructions)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "29_a_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR",
		page: "pages/29_a_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR.md",
		title: "29 a writing a book as a famous author",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Establishing the AI Agent](#establishing-the-ai-agent)\n  * [Writing the Story](#writing-the-story)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "29_b_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR",
		page: "pages/29_b_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR.md",
		title: "29 b writing a book as a famous author",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Import Necessary Modules](#import-necessary-modules)\n  * [Initialize the GPT Model Adapter](#initialize-the-gpt-model-adapter)\n  * [Define Function Capability](#define-function-capability)\n  * [Assign a Task to the Agent](#assign-a-task-to-the-agent)\n- [Expected Output](#expected-output)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "30_OPENAI_GPT_CUSTOM_FUNCTION_CALL",
		page: "pages/30_OPENAI_GPT_CUSTOM_FUNCTION_CALL.md",
		title: "30 openai gpt custom function call",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Setting Up a Language Model](#setting-up-a-language-model)\n  * [Constructing System Instruction with Lingo](#constructing-system-instruction-with-lingo)\n  * [Guiding the Model's Output](#guiding-the-models-output)\n- [Expected Output](#expected-output)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "31_a_USING_LINGO_WITH_INSTRUCTIONS",
		page: "pages/31_a_USING_LINGO_WITH_INSTRUCTIONS.md",
		title: "31 a using lingo with instructions",
	},
	{
		toc: "- [Overview](#overview)\n- [Prerequisites](#prerequisites)\n- [Guide](#guide)\n  * [Crafting Instructions Using Lingo](#crafting-instructions-using-lingo)\n  * [Configuring a Persona](#configuring-a-persona)\n  * [Generating Instructions with Lingo and Persona](#generating-instructions-with-lingo-and-persona)\n- [Summary](#summary)\n- [Tags](#tags)",
		name: "31_b_USING_LINGO_WITH_PERSONA_AND_INSTRUCTIONS",
		page: "pages/31_b_USING_LINGO_WITH_PERSONA_AND_INSTRUCTIONS.md",
		title: "31 b using lingo with persona and instructions",
	},
];
export default pages;
