export default [
	{
		root: "",
		dir: "pages",
		base: "01_GETTING_STARTED.md",
		ext: ".md",
		name: "01_GETTING_STARTED",
		page: "pages/01_GETTING_STARTED.md",
		title: "01 getting started",
	},
	{
		root: "",
		dir: "pages",
		base: "02_SYSTEM_INSTRUCTIONS.md",
		ext: ".md",
		name: "02_SYSTEM_INSTRUCTIONS",
		page: "pages/02_SYSTEM_INSTRUCTIONS.md",
		title: "02 system instructions",
	},
	{
		root: "",
		dir: "pages",
		base: "03_CREATING_A_SEQUENCE.md",
		ext: ".md",
		name: "03_CREATING_A_SEQUENCE",
		page: "pages/03_CREATING_A_SEQUENCE.md",
		title: "03 creating a sequence",
	},
	{
		root: "",
		dir: "pages",
		base: "04_a_SETUP_WEAVIATE_VECTOR_DATABASE.md",
		ext: ".md",
		name: "04_a_SETUP_WEAVIATE_VECTOR_DATABASE",
		page: "pages/04_a_SETUP_WEAVIATE_VECTOR_DATABASE.md",
		title: "04 a setup weaviate vector database",
	},
	{
		root: "",
		dir: "pages",
		base: "04_b_USING_WEAVIATE_VECTOR_DATABASE.md",
		ext: ".md",
		name: "04_b_USING_WEAVIATE_VECTOR_DATABASE",
		page: "pages/04_b_USING_WEAVIATE_VECTOR_DATABASE.md",
		title: "04 b using weaviate vector database",
	},
	{
		root: "",
		dir: "pages",
		base: "05_GENERATE_IMAGES_WITH_DALL-E.md",
		ext: ".md",
		name: "05_GENERATE_IMAGES_WITH_DALL-E",
		page: "pages/05_GENERATE_IMAGES_WITH_DALL-E.md",
		title: "05 generate images with dall e",
	},
	{
		root: "",
		dir: "pages",
		base: "06_GENERATING_IMAGES_WITH_STABLE-DIFFUSION.md",
		ext: ".md",
		name: "06_GENERATING_IMAGES_WITH_STABLE-DIFFUSION",
		page: "pages/06_GENERATING_IMAGES_WITH_STABLE-DIFFUSION.md",
		title: "06 generating images with stable diffusion",
	},
	{
		root: "",
		dir: "pages",
		base: "07_a_LET_AI_AGENTS_COMPETE_GENERATED_CONTENT.md",
		ext: ".md",
		name: "07_a_LET_AI_AGENTS_COMPETE_GENERATED_CONTENT",
		page: "pages/07_a_LET_AI_AGENTS_COMPETE_GENERATED_CONTENT.md",
		title: "07 a let ai agents compete generated content",
	},
	{
		root: "",
		dir: "pages",
		base: "07_b_LET_AI_AGENTS_RATE_GENERATED_CONTENT.md",
		ext: ".md",
		name: "07_b_LET_AI_AGENTS_RATE_GENERATED_CONTENT",
		page: "pages/07_b_LET_AI_AGENTS_RATE_GENERATED_CONTENT.md",
		title: "07 b let ai agents rate generated content",
	},
	{
		root: "",
		dir: "pages",
		base: "08_MAKING_PRECISE_CALCULATIONS.md",
		ext: ".md",
		name: "08_MAKING_PRECISE_CALCULATIONS",
		page: "pages/08_MAKING_PRECISE_CALCULATIONS.md",
		title: "08 making precise calculations",
	},
	{
		root: "",
		dir: "pages",
		base: "09_CREATING_PERSONAS.md",
		ext: ".md",
		name: "09_CREATING_PERSONAS",
		page: "pages/09_CREATING_PERSONAS.md",
		title: "09 creating personas",
	},
	{
		root: "",
		dir: "pages",
		base: "10_a_PARALLEL_AGENTS_WORKING_TOGETHER.md",
		ext: ".md",
		name: "10_a_PARALLEL_AGENTS_WORKING_TOGETHER",
		page: "pages/10_a_PARALLEL_AGENTS_WORKING_TOGETHER.md",
		title: "10 a parallel agents working together",
	},
	{
		root: "",
		dir: "pages",
		base: "10_b_PARALLEL_AGENTS_WORK_MERGED_TOGETHER.md",
		ext: ".md",
		name: "10_b_PARALLEL_AGENTS_WORK_MERGED_TOGETHER",
		page: "pages/10_b_PARALLEL_AGENTS_WORK_MERGED_TOGETHER.md",
		title: "10 b parallel agents work merged together",
	},
	{
		root: "",
		dir: "pages",
		base: "11_a_OPTIMIZE_GENERATED_CODE.md",
		ext: ".md",
		name: "11_a_OPTIMIZE_GENERATED_CODE",
		page: "pages/11_a_OPTIMIZE_GENERATED_CODE.md",
		title: "11 a optimize generated code",
	},
	{
		root: "",
		dir: "pages",
		base: "11_b_OPTIMIZE_GENERATED_CODE.md",
		ext: ".md",
		name: "11_b_OPTIMIZE_GENERATED_CODE",
		page: "pages/11_b_OPTIMIZE_GENERATED_CODE.md",
		title: "11 b optimize generated code",
	},
	{
		root: "",
		dir: "pages",
		base: "12_UNDERSTANDING_VERBOSITY_OF_HYV_AGENTS.md",
		ext: ".md",
		name: "12_UNDERSTANDING_VERBOSITY_OF_HYV_AGENTS",
		page: "pages/12_UNDERSTANDING_VERBOSITY_OF_HYV_AGENTS.md",
		title: "12 understanding verbosity of hyv agents",
	},
	{
		root: "",
		dir: "pages",
		base: "13_a_ASSIGNING_A_TASK_TO_AN_AGENT.md",
		ext: ".md",
		name: "13_a_ASSIGNING_A_TASK_TO_AN_AGENT",
		page: "pages/13_a_ASSIGNING_A_TASK_TO_AN_AGENT.md",
		title: "13 a assigning a task to an agent",
	},
	{
		root: "",
		dir: "pages",
		base: "13_b_ASSIGNING_A_TASK_TO_AN_AGENT.md",
		ext: ".md",
		name: "13_b_ASSIGNING_A_TASK_TO_AN_AGENT",
		page: "pages/13_b_ASSIGNING_A_TASK_TO_AN_AGENT.md",
		title: "13 b assigning a task to an agent",
	},
	{
		root: "",
		dir: "pages",
		base: "14_a_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		ext: ".md",
		name: "14_a_GENERATE_A_STORY_WITH_INLINE_IMAGES",
		page: "pages/14_a_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		title: "14 a generate a story with inline images",
	},
	{
		root: "",
		dir: "pages",
		base: "14_b_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		ext: ".md",
		name: "14_b_GENERATE_A_STORY_WITH_INLINE_IMAGES",
		page: "pages/14_b_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		title: "14 b generate a story with inline images",
	},
	{
		root: "",
		dir: "pages",
		base: "14_c_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		ext: ".md",
		name: "14_c_GENERATE_A_STORY_WITH_INLINE_IMAGES",
		page: "pages/14_c_GENERATE_A_STORY_WITH_INLINE_IMAGES.md",
		title: "14 c generate a story with inline images",
	},
	{
		root: "",
		dir: "pages",
		base: "15_a_CREATING_CUSTOM_MODEL_ADAPTERS.md",
		ext: ".md",
		name: "15_a_CREATING_CUSTOM_MODEL_ADAPTERS",
		page: "pages/15_a_CREATING_CUSTOM_MODEL_ADAPTERS.md",
		title: "15 a creating custom model adapters",
	},
	{
		root: "",
		dir: "pages",
		base: "15_b_CREATING_CUSTOM_MODEL_ADAPTERS.md",
		ext: ".md",
		name: "15_b_CREATING_CUSTOM_MODEL_ADAPTERS",
		page: "pages/15_b_CREATING_CUSTOM_MODEL_ADAPTERS.md",
		title: "15 b creating custom model adapters",
	},
	{
		root: "",
		dir: "pages",
		base: "16_a_CREATING_A_MONGODB_STORE_ADAPTER.md",
		ext: ".md",
		name: "16_a_CREATING_A_MONGODB_STORE_ADAPTER",
		page: "pages/16_a_CREATING_A_MONGODB_STORE_ADAPTER.md",
		title: "16 a creating a mongodb store adapter",
	},
	{
		root: "",
		dir: "pages",
		base: "16_b_CREATING_A_MONGODB_STORE_ADAPTER.md",
		ext: ".md",
		name: "16_b_CREATING_A_MONGODB_STORE_ADAPTER",
		page: "pages/16_b_CREATING_A_MONGODB_STORE_ADAPTER.md",
		title: "16 b creating a mongodb store adapter",
	},
	{
		root: "",
		dir: "pages",
		base: "17_a_CREATING_A_PRISMA_STORE_ADAPTER.md",
		ext: ".md",
		name: "17_a_CREATING_A_PRISMA_STORE_ADAPTER",
		page: "pages/17_a_CREATING_A_PRISMA_STORE_ADAPTER.md",
		title: "17 a creating a prisma store adapter",
	},
	{
		root: "",
		dir: "pages",
		base: "17_b_CREATING_A_PRISMA_STORE_ADAPTER.md",
		ext: ".md",
		name: "17_b_CREATING_A_PRISMA_STORE_ADAPTER",
		page: "pages/17_b_CREATING_A_PRISMA_STORE_ADAPTER.md",
		title: "17 b creating a prisma store adapter",
	},
	{
		root: "",
		dir: "pages",
		base: "18_CREATING_A_SIMPLE_CHAT_WITH_PERSONA.md",
		ext: ".md",
		name: "18_CREATING_A_SIMPLE_CHAT_WITH_PERSONA",
		page: "pages/18_CREATING_A_SIMPLE_CHAT_WITH_PERSONA.md",
		title: "18 creating a simple chat with persona",
	},
	{
		root: "",
		dir: "pages",
		base: "19_HANDLING_ERRORS.md",
		ext: ".md",
		name: "19_HANDLING_ERRORS",
		page: "pages/19_HANDLING_ERRORS.md",
		title: "19 handling errors",
	},
	{
		root: "",
		dir: "pages",
		base: "20_WHAT_DOES_HYV_MEAN_WHAT_IS_HYV.md",
		ext: ".md",
		name: "20_WHAT_DOES_HYV_MEAN_WHAT_IS_HYV",
		page: "pages/20_WHAT_DOES_HYV_MEAN_WHAT_IS_HYV.md",
		title: "20 what does hyv mean what is hyv",
	},
	{
		root: "",
		dir: "pages",
		base: "21_BEFORE_AFTER_FINALLY_METHODS_OF_AGENT.md",
		ext: ".md",
		name: "21_BEFORE_AFTER_FINALLY_METHODS_OF_AGENT",
		page: "pages/21_BEFORE_AFTER_FINALLY_METHODS_OF_AGENT.md",
		title: "21 before after finally methods of agent",
	},
	{
		root: "",
		dir: "pages",
		base: "22_HYV_REST_API_NEXTJS_API_ROUTE_SERVERLESS.md",
		ext: ".md",
		name: "22_HYV_REST_API_NEXTJS_API_ROUTE_SERVERLESS",
		page: "pages/22_HYV_REST_API_NEXTJS_API_ROUTE_SERVERLESS.md",
		title: "22 hyv rest api nextjs api route serverless",
	},
	{
		root: "",
		dir: "pages",
		base: "23_HYV_REST_API_EXPRESSJS_SERVER.md",
		ext: ".md",
		name: "23_HYV_REST_API_EXPRESSJS_SERVER",
		page: "pages/23_HYV_REST_API_EXPRESSJS_SERVER.md",
		title: "23 hyv rest api expressjs server",
	},
	{
		root: "",
		dir: "pages",
		base: "24_ADJUSTING_MODEL_ADAPTER_OPTIONS.md",
		ext: ".md",
		name: "24_ADJUSTING_MODEL_ADAPTER_OPTIONS",
		page: "pages/24_ADJUSTING_MODEL_ADAPTER_OPTIONS.md",
		title: "24 adjusting model adapter options",
	},
	{
		root: "",
		dir: "pages",
		base: "25_ADJUSTING_AGENT_OPTIONS.md",
		ext: ".md",
		name: "25_ADJUSTING_AGENT_OPTIONS",
		page: "pages/25_ADJUSTING_AGENT_OPTIONS.md",
		title: "25 adjusting agent options",
	},
	{
		root: "",
		dir: "pages",
		base: "26_ADVANCED_USE_CASES_FOR_HYV_AGENTS.md",
		ext: ".md",
		name: "26_ADVANCED_USE_CASES_FOR_HYV_AGENTS",
		page: "pages/26_ADVANCED_USE_CASES_FOR_HYV_AGENTS.md",
		title: "26 advanced use cases for hyv agents",
	},
	{
		root: "",
		dir: "pages",
		base: "27_SIMPLICITY_POWERFUL_HIGH_POTENTIAL_OF_HYV_AGENTS.md",
		ext: ".md",
		name: "27_SIMPLICITY_POWERFUL_HIGH_POTENTIAL_OF_HYV_AGENTS",
		page: "pages/27_SIMPLICITY_POWERFUL_HIGH_POTENTIAL_OF_HYV_AGENTS.md",
		title: "27 simplicity powerful high potential of hyv agents",
	},
	{
		root: "",
		dir: "pages",
		base: "28_a_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER.md",
		ext: ".md",
		name: "28_a_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER",
		page: "pages/28_a_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER.md",
		title: "28 a ai debate two agents talking to each other",
	},
	{
		root: "",
		dir: "pages",
		base: "28_b_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER.md",
		ext: ".md",
		name: "28_b_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER",
		page: "pages/28_b_AI_DEBATE_TWO_AGENTS_TALKING_TO_EACH_OTHER.md",
		title: "28 b ai debate two agents talking to each other",
	},
	{
		root: "",
		dir: "pages",
		base: "29_a_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR.md",
		ext: ".md",
		name: "29_a_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR",
		page: "pages/29_a_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR.md",
		title: "29 a writing a book as a famous author",
	},
	{
		root: "",
		dir: "pages",
		base: "29_b_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR.md",
		ext: ".md",
		name: "29_b_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR",
		page: "pages/29_b_WRITING_A_BOOK_AS_A_FAMOUS_AUTHOR.md",
		title: "29 b writing a book as a famous author",
	},
	{
		root: "",
		dir: "pages",
		base: "30_OPENAI_GPT_CUSTOM_FUNCTION_CALL.md",
		ext: ".md",
		name: "30_OPENAI_GPT_CUSTOM_FUNCTION_CALL",
		page: "pages/30_OPENAI_GPT_CUSTOM_FUNCTION_CALL.md",
		title: "30 openai gpt custom function call",
	},
	{
		root: "",
		dir: "pages",
		base: "31_a_USING_LINGO_WITH_INSTRUCTIONS.md",
		ext: ".md",
		name: "31_a_USING_LINGO_WITH_INSTRUCTIONS",
		page: "pages/31_a_USING_LINGO_WITH_INSTRUCTIONS.md",
		title: "31 a using lingo with instructions",
	},
	{
		root: "",
		dir: "pages",
		base: "31_b_USING_LINGO_WITH_PERSONA_AND_INSTRUCTIONS.md",
		ext: ".md",
		name: "31_b_USING_LINGO_WITH_PERSONA_AND_INSTRUCTIONS",
		page: "pages/31_b_USING_LINGO_WITH_PERSONA_AND_INSTRUCTIONS.md",
		title: "31 b using lingo with persona and instructions",
	},
];
